CREATE TABLE USER_PROFILE_REGISTRATION (
    REGISTER_ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    BIRTHDATE DATETIME NOT NULL,
    NATIONALITY VARCHAR(50) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    STATE VARCHAR(80) NOT NULL,
    ZIP_CODE INT NOT NULL,
    COMPLETE_ADDRESS VARCHAR(255),
    GENDER VARCHAR(20) NOT NULL,
    USER_TYPE VARCHAR(10) NOT NULL,
    EMAIL VARCHAR(80),
    PASSPHRASE VARCHAR(255) NOT NULL,
    DATE_CREATED DATETIME
);


CREATE TABLE USER_ACCOUNT (
    USER_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    FK_REGISTER_ID INT NOT NULL,
    FOREIGN KEY (FK_REGISTER_ID) REFERENCES USER_PROFILE_REGISTRATION(REGISTER_ID)
);

--TRIGGER 
DELIMITER //

CREATE TRIGGER `INSERT_UPR_TRIGGER`
AFTER INSERT
ON `user_profile_registration`
FOR EACH ROW
BEGIN
  INSERT INTO `user_account`(EMAIL, PASSWORD, FK_REGISTER_ID2)
  VALUES (NEW.EMAIL, NEW.PASSPHRASE, NEW.REGISTER_ID); //user_profile_registration
END //

DELIMITER ;